// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkdDNGwv26mNJpDUWS0ADJSlmt7Nz25GE',
    appId: '1:766556321385:web:52d11ba3b8c50ba76e94f8',
    messagingSenderId: '766556321385',
    projectId: 'health-for-all-f7c3f',
    authDomain: 'health-for-all-f7c3f.firebaseapp.com',
    storageBucket: 'health-for-all-f7c3f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPdS4KxRKi4U-BHQiKOSEHXcAEA9gpM0M',
    appId: '1:766556321385:android:c02ec189c6b44d1a6e94f8',
    messagingSenderId: '766556321385',
    projectId: 'health-for-all-f7c3f',
    storageBucket: 'health-for-all-f7c3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFvuMRGqW_zNn51OnlRzPxLyYiWLyBy1A',
    appId: '1:766556321385:ios:c8daf281b4ef28d66e94f8',
    messagingSenderId: '766556321385',
    projectId: 'health-for-all-f7c3f',
    storageBucket: 'health-for-all-f7c3f.appspot.com',
    androidClientId: '766556321385-ef9eie3kdsfa6sulein1r34qa39icv6d.apps.googleusercontent.com',
    iosClientId: '766556321385-5k1g436jpp8g5usdlhnjreu353ul6u33.apps.googleusercontent.com',
    iosBundleId: 'com.example.hfa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFvuMRGqW_zNn51OnlRzPxLyYiWLyBy1A',
    appId: '1:766556321385:ios:c8daf281b4ef28d66e94f8',
    messagingSenderId: '766556321385',
    projectId: 'health-for-all-f7c3f',
    storageBucket: 'health-for-all-f7c3f.appspot.com',
    androidClientId: '766556321385-ef9eie3kdsfa6sulein1r34qa39icv6d.apps.googleusercontent.com',
    iosClientId: '766556321385-5k1g436jpp8g5usdlhnjreu353ul6u33.apps.googleusercontent.com',
    iosBundleId: 'com.example.hfa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkdDNGwv26mNJpDUWS0ADJSlmt7Nz25GE',
    appId: '1:766556321385:web:5f135e1a22eaef476e94f8',
    messagingSenderId: '766556321385',
    projectId: 'health-for-all-f7c3f',
    authDomain: 'health-for-all-f7c3f.firebaseapp.com',
    storageBucket: 'health-for-all-f7c3f.appspot.com',
  );
}
